### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by wesselstam** [imanghafoori1/abstract_php_filesystem#1]
Laravel microscope depends on this package but there is no PHP 8.2 support yet.

I saw it has been added to the master branch but that version hasn't been tagged yet, so Laravel microscope can't use it.

Could you please add a tag to that version?

Thanks for all the efforts!
Cheers

**Comment by ThomasEnssner** [comment]
Using your nice Laravel-Microscope with php 8.2 would be great. *push*

**Comment by imanghafoori1** [comment]
@ThomasEnssner I did it.
Please tell me if there were any other problems.

**Comment by ThomasEnssner** [comment]
We also need the package [imanghafoori1/php-smart-search-replace](https://github.com/imanghafoori1/php-smart-search-replace) to allow php 8.2

Would be great to have this patched, too.

**Comment by imanghafoori1** [comment]
that one is also patched, what else?

**Comment by ThomasEnssner** [comment]
Think you should change [line 22 in composer.json of microscope](https://github.com/imanghafoori1/laravel-microscope/blob/cddbe5aff15f7b132167d686f42296195bbac6df/composer.json#L22)

from `"imanghafoori/php-search-replace": "1.1.8"` 
to `"imanghafoori/php-search-replace": "^1.1.8"`

**Comment by imanghafoori1** [comment]
Done.

**Comment by ThomasEnssner** [comment]
Sorry... I missed the missing php8.2 requirement of [imanghafoori1/smart-realtime-facades](https://github.com/imanghafoori1/smart-realtime-facades)

**Comment by imanghafoori1** [comment]
Done.
